# Exported from:        http://dhivya:5516/
# Release version:      26.1.0-SNAPSHOT
# Date created:         Thu Sep 25 20:00:39 IST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_test_2.yaml
