# Exported from:        http://dhivya:5516/
# Release version:      25.3.0-SNAPSHOT
# Date created:         Wed Oct 08 16:16:11 IST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_t2.yaml
