# Exported from:        http://MacBook-Pro-od-Paula:5516/
# Release version:      24.1.0

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_tem.yaml
  - Trigger_trig.yaml
