# Exported from:        http://dhivya:5516/
# Release version:      26.1.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_configure_release.yaml
  - Template_guided_tour_for_release_managers.yaml
  - Template_sample_release_template.yaml
  - Template_welcome_to_release.yaml
