# Exported from:        http://dhivya:5516/
# Release version:      26.1.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: test
spec:
- name: test2
  type: time.Schedule
  releaseTitle: testtii
  template: test
  releaseFolder: ./
  periodicity: 0 0 * * * *
