# Exported from:        http://dhivya:5516/
# Release version:      26.1.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: test
spec:
- name: test
  type: time.Schedule
  releaseTitle: testrel
  template: test
  releaseFolder: test-out/test-out-out
  periodicity: 0 0 * * * *
