# Exported from:        http://dhivya:5516/
# Release version:      26.1.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: test
spec:
- template: tresssf//
  scheduledStartDate: 2026-01-22T09:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
  author: admin
