# Exported from:        http://dhivya:5516/
# Release version:      24.1.9-SNAPSHOT
# Date created:         Mon Sep 30 13:17:47 IST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_Child.yaml
  - Template_Parent.yaml
