# Exported from:        http://dhivya:5516/
# Release version:      24.1.9-SNAPSHOT
# Date created:         Mon Sep 30 13:17:47 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: CRTTest
spec:
- template: Child
  scheduledStartDate: 2024-04-08T18:30:00+05:30
  dueDate: 2024-04-08T19:30:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: Script
      type: xlrelease.ScriptTask
      script: |-
        print releaseVariables['ListBox']
        print releaseVariables['stringVal']
        print releaseVariables['boolVal']
        print releaseVariables['numVal']
  variables:
  - type: xlrelease.StringVariable
    key: ListBox
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - dog
      - cat
      - bird
    value: cat
  - type: xlrelease.StringVariable
    key: stringVal
    value: fooBar
  - type: xlrelease.BooleanVariable
    key: boolVal
  - type: xlrelease.IntegerVariable
    key: numVal
    value: 999
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Child_scriptUserPassword"
  riskProfile: Default risk profile
