# Exported from:        http://dhivya:5516/
# Release version:      26.1.0-SNAPSHOT
# Date created:         Mon Nov 24 17:17:17 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: teft
  home: tesst%2Fteft/teft
spec:
- pattern: tttt
  stages:
  - stage: New Stage
