# Exported from:        http://dhivya:5516/
# Release version:      26.1.0-SNAPSHOT
# Date created:         Mon Nov 24 14:53:15 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: tesst
spec:
- pattern: tesst
  stages:
  - stage: New Stage (2)
  - stage: New Stage (1)
  - stage: New Stage
