# Exported from:        http://dhivya:5516/
# Release version:      24.1.6
# Date created:         Tue Sep 17 13:41:17 IST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_Child.yaml
  - Template_Parent.yaml
