# Exported from:        http://dhivya:5516/
# Release version:      25.3.0-SNAPSHOT
# Date created:         Thu Apr 17 17:57:25 IST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_test%2Ftest%2F%2Ftest.yaml
