# Exported from:        http://dhivya:5516/
# Release version:      25.3.0-SNAPSHOT
# Date created:         Thu Apr 17 15:58:29 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: test%2Ftest1
  home: test/test1/test%2Ftest1
spec:
- name: test///test/////test
  type: time.Schedule
  releaseTitle: test
  template: test///test/test1
  periodicity: 0 0 * * * *
