# Exported from:        http://dhivya:5516/
# Release version:      25.3.0-SNAPSHOT
# Date created:         Thu Apr 17 15:58:29 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: test%2Ftest1
  home: test/test1/test%2Ftest1
spec:
- template: test//test2
  scheduledStartDate: 2025-04-17T09:00:00+05:30
  phases:
  - phase: Workflow tasks
  kind: WORKFLOW
  disableNotifications: true
  author: admin
  defaultTargetFolder: test/test1
